### PR TITLE
#4: Failed to run report generator

### LINKED ISSUE #4: Failed to run report generator
When using the XLT Jenkins plugin as part of a Jenkins job to perform a load test with XLT, the job may sometimes fail to run the report generator: 

```
    16:09:07  -------------------   --------   ----------------   ----------   ---------   ---------   ------------   ---------   -------------   --------
    16:09:07  T1                    Finished        0 of     10       49,921      0.07 s      0.36 s        1:00:00           0       44   (0%)       100%
    16:09:07  T2                    Finished        0 of     10       49,913      0.56 s      0.38 s        0:59:59           0       30   (0%)       100%
    16:09:07  T3                    Finished        0 of     10       49,913      0.07 s      0.35 s        0:59:59           0       57   (0%)       100%
    16:09:07  T4                    Finished        0 of    400    1,796,801      0.31 s      0.42 s        0:59:59           0      342   (0%)       100%
    16:09:07  T5                    Finished        0 of     10       49,915      0.03 s      0.38 s        1:00:00           0       32   (0%)       100%
    16:09:07  T6                    Finished        0 of    400    3,491,399      0.05 s      0.28 s        0:59:59           0    7,504   (0%)       100%
    16:09:07  T7                    Finished        0 of     10      144,532      0.67 s      0.25 s        1:00:00           0        0   (0%)       100%
    16:09:07  T8                    Finished        0 of     10      117,898      0.46 s      0.31 s        1:00:00           0    1,630   (1%)       100%
    16:09:07  T9                    Finished        0 of     10       49,915      0.13 s      0.45 s        1:00:00           0        0   (0%)       100%
    16:09:07  T10                   Finished        0 of     10       49,914      0.04 s      0.38 s        0:59:59           0       31   (0%)       100%
    16:09:07  -------------------   --------   ----------------   ----------   ---------   ---------   ------------   ---------   -------------   --------
    16:09:07  Totals                Finished        0 of    880    5,850,121           /           /        1:00:00           0    9,670   (0%)       100%
    16:09:07  
    16:09:07  Downloading test results... Please be patient, it might take some time...
    16:09:54      0% ... 10% ... 20% ... 30% ... 40% ... 50% ... 60% ... 70% ... 80% ... 90% ... 100% - OK
    16:09:54  
    16:09:54  
    16:09:54  Results have been downloaded to: /build/tmp-xlt/<job-name>/211/8053307A-19CB-4726-BED4-6427E909BA33/xlt/results/20220312-150907
    16:09:54  Master controller returned with exit code: 0
    16:09:54  -----------------------------------------------------------------
    16:09:54  Running report generator ...
    16:09:54  
    16:09:54  [bin] $ ./create_report.sh -o /build/tmp-xlt/<job-name>/211/8053307A-19CB-4726-BED4-6427E909BA33/xlt/report -linkToResults no /build/tmp-xlt/<job-name>/211/8053307A-19CB-4726-BED4-6427E909BA33/xlt/results -Dmonitoring.trackSlowestRequests=true
    16:09:54  Build failed: Process working directory '/build/tmp-xlt/<job-name>/211/8053307A-19CB-4726-BED4-6427E909BA33/xlt/bin' doesn't exist!
```
Looks as if the temporary copy of XLT used for the load test is compromised.

### PR DESCRIPTION
**Pull request by jowerner**
Don't delete temporary XLT folders that don't belong to the current run as this would harm parallel runs of this job/project.

### CODE REVIEW

File: src/main/java/com/xceptance/xlt/tools/jenkins/XltTask.java [hunk 1]
```diff
@@ -579,14 +579,7 @@ private void performPostTestSteps(final Run<?, ?> run, final Launcher launcher,
...
         {
-            FilePath tempProjectFolder = getTemporaryXltProjectFolder(run, launcher);
-            tempProjectFolder.deleteRecursive();
-
-            FilePath tempFolder = getTemporaryXltBaseFolder(run, launcher);
-            if (tempFolder.exists() && (tempFolder.list() == null || tempFolder.list().isEmpty()))
-            {
-                tempFolder.delete();
-            }
+            getTemporaryXltBuildFolder(run, launcher).deleteRecursive();
```
Comment (h-arlt) [inline src/main/java/com/xceptance/xlt/tools/jenkins/XltTask.java]: This will delete the temporary XLT folders of all steps (job might invoke our plugin multiple times) of this run. Shouldn't we change that to delete the temporary XLT folder of the current run and stepId only?
 ```suggestion
            getTemporaryXltFolder(run, launcher).deleteRecursive();
```

**Review by h-arlt — CHANGES_REQUESTED** [review]

File: src/main/java/com/xceptance/xlt/tools/jenkins/XltTask.java (hunk 1 above)
Comment (jowerner) [reply src/main/java/com/xceptance/xlt/tools/jenkins/XltTask.java]: Done. Furthermore, XLT copies are now managed in a flat directory structure to avoid leaving empty project directories behind.

**Review by h-arlt — APPROVED** [review]
